In [ ]:
pip install pandas numpy scikit-learn scipy matplotlib

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import PowerTransformer
from scipy.stats.mstats import winsorize
from scipy.stats import boxcox
import matplotlib.pyplot as plt

In [ ]:
# Load dataset

df = pd.read_csv('covid.csv')

# Display first 5 rows
print(df.head())

  Country/Region  Confirmed  Deaths  Recovered  Active  New cases  New deaths  \
0    Afghanistan      36263    1269      25198    9796        106          10   
1        Albania       4880     144       2745    1991        117           6   
2        Algeria      27973    1163      18837    7973        616           8   
3        Andorra        907      52        803      52         10           0   
4         Angola        950      41        242     667         18           1   

   New recovered  Deaths / 100 Cases  Recovered / 100 Cases  \
0             18                3.50                  69.49   
1             63                2.95                  56.25   
2            749                4.16                  67.34   
3              0                5.73                  88.53   
4              0                4.32                  25.47   

   Deaths / 100 Recovered  Confirmed last week  1 week change  \
0                    5.04                35526            737   
1   

In [ ]:
print(df.select_dtypes(include=np.number).columns)

Index(['Confirmed', 'Deaths', 'Recovered', 'Active', 'New cases', 'New deaths',
       'New recovered', 'Deaths / 100 Cases', 'Recovered / 100 Cases',
       'Deaths / 100 Recovered', 'Confirmed last week', '1 week change',
       '1 week % increase'],
      dtype='object')


In [ ]:
winsorized_data = winsorize(df['Confirmed'], limits=[0.05, 0.05])

print(winsorized_data)

[ 36263   4880  27973    907    950     86 167416  37390  15303  20558
  30446    382  39482 226225    110  67251  66428     48   1770     99
  71181  10498    739 293606    141  10621   1100    350    378   2328
    226  17110 116458   4599    922 293606  86783 257101    354   3200
   8844  15841  15655   4881   2532   1060  15516  13761   5059     27
  64156  81161  92482  15035   3071    265   2034   2316  14547     27
   7398 220352   7189    326   1137 207112  33624   4227     27     27
  45309   7055   1954    389   7340     27  39741   4448   1854 293606
 100303 293606 112585  25892  63985 246286    853  31142   1176  84648
  17975   7413  64379  33296     27   1219   3882    505   1167   2827
     86   2019   6321   9690   3664   8904   3369   2513    701   6208
    344 293606  23154    116    289   2893  20887   1701   1843  18752
  53413   1557   3439   1132  41180  10213   9132  77058 274289  61442
     62   4548 293606  82040  43402  50299 109597  45902 293606   1879
     2

In [ ]:
import pandas as pd
from scipy.stats.mstats import winsorize

df = pd.read_csv('preprocessing_dataset.csv')


age_data = df['Age'].dropna()

print("Original Data:")
print(age_data)


winsorized_age = winsorize(age_data, limits=[0.20, 0.20])

print("\nWinsorized Data:")
print(winsorized_age)

Original Data:
0     25.0
1     30.0
3     40.0
4     22.0
5     35.0
6    120.0
7     28.0
8     29.0
9     27.0
Name: Age, dtype: float64

Winsorized Data:
[25. 30. 40. 25. 35. 40. 28. 29. 27.]


In [ ]:
import numpy as np

log_age = np.log1p(age_data)

print(log_age)

0    3.258097
1    3.433987
3    3.713572
4    3.135494
5    3.583519
6    4.795791
7    3.367296
8    3.401197
9    3.332205
Name: Age, dtype: float64


In [ ]:
from scipy.stats import boxcox

positive_age = age_data[age_data > 0]

boxcox_data, lambda_value = boxcox(positive_age)

print(boxcox_data)
print(lambda_value)

[0.51499069 0.51529073 0.51559329 0.51470732 0.51547356 0.51595046
 0.51518945 0.51524265 0.51513036]
-1.9379894538574858


In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

scaled_age = scaler.fit_transform(df[['Age']].dropna())

print(scaled_age)

[[0.03061224]
 [0.08163265]
 [0.18367347]
 [0.        ]
 [0.13265306]
 [1.        ]
 [0.06122449]
 [0.07142857]
 [0.05102041]]


In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

standard_age = scaler.fit_transform(df[['Age']].dropna())

print(standard_age)

[[-0.50401021]
 [-0.33087693]
 [ 0.01538962]
 [-0.60789017]
 [-0.15774365]
 [ 2.78552206]
 [-0.40013024]
 [-0.36550359]
 [-0.4347569 ]]
